title: History for all
description: thedoorisonyourleft
author: thedoorisonyourleft
avatar: /logo.png
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: kr

theme: jekyll-theme-leap-day
